[plugin] fix unicode vs. byte array handling in string IO
Causes a nosetests failure on python3:

    ======================================================================
    ERROR: test_glob_file_over_limit (plugin_tests.AddCopySpecTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/breeves/src/git/sos/tests/plugin_tests.py", line 269, in test_glob_file_over_limit
        self.mp.add_copy_spec_limit("/tmp/tmp*", 1)
      File "/home/breeves/src/git/sos/sos/plugins/__init__.py", line 414, in add_copy_spec_limit
        self.add_string_as_file(tail(_file, sizelimit), strfile)
      File "/home/breeves/src/git/sos/sos/plugins/__init__.py", line 520, in add_string_as_file
        content = "..." + content.splitlines()[0]
    TypeError: Can't convert 'bytes' object to str implicitly

    ======================================================================
    ERROR: test_single_file_over_limit (plugin_tests.AddCopySpecTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/breeves/src/git/sos/tests/plugin_tests.py", line 253, in test_single_file_over_limit
        self.mp.add_copy_spec_limit(fn, 1)
      File "/home/breeves/src/git/sos/sos/plugins/__init__.py", line 414, in add_copy_spec_limit
        self.add_string_as_file(tail(_file, sizelimit), strfile)
      File "/home/breeves/src/git/sos/sos/plugins/__init__.py", line 520, in add_string_as_file
        content = "..." + content.splitlines()[0]
    TypeError: Can't convert 'bytes' object to str implicitly

    ----------------------------------------------------------------------

Signed-off-by: Bryn M. Reeves <bmr@redhat.com>