Fix exception in Policy::get_pkg_list()
If the current working directory (as reported by getcwd()) does
not exist the package manager component of the policy may fail
to initialise:

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Traceback (most recent call last):
  File "/sbin/sosreport", line 23, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1228, in main
    sos = SoSReport(args)
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 530, in __init__
    self.policy = sos.policies.load()
  File "/usr/lib/python2.7/site-packages/sos/policies/__init__.py", line 39, in load
    cache['policy'] = policy()
  File "/usr/lib/python2.7/site-packages/sos/policies/redhat.py", line 165, in __init__
    super(FedoraPolicy, self).__init__()
  File "/usr/lib/python2.7/site-packages/sos/policies/redhat.py", line 49, in __init__
    if self.package_manager.all_pkgs()['filesystem']['version'][0] == '3':
  File "/usr/lib/python2.7/site-packages/sos/policies/__init__.py", line 108, in all_pkgs
    self.packages = self.get_pkg_list()
  File "/usr/lib/python2.7/site-packages/sos/policies/__init__.py", line 95, in get_pkg_list
    name, version = pkg.split("|")
ValueError: need more than 1 value to unpack

Fix this by ensuring that the string contains at least one pipe
character before splitting.

There are many reasons that the package manager could spit out
unexpected lines with the package list so this improves the
general robustness of this code.

Fixes RHBZ#1091683.

Signed-off-by: Bryn M. Reeves <bmr@redhat.com>