[networking] test nmcli status before using output
The networking module assumes that nmcli commands succeed if the
results object is not None; this is not valid and will lead to
errors in subsequent commands if the call returned an error
message instead of the expected content:

  [plugin:networking] collecting output of 'nmcli con show conf 'Error: nmcli (0.9.10.0) and NetworkManager (unknown) versions don't match. Force execution using --nocheck, but the results are unpredictable.''
  Traceback (most recent call last):
    File "/usr/sbin/sosreport", line 25, in <module>
      main(sys.argv[1:])
    File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1459, in main
      sos.execute()
  ValueError: No closing quotation

Signed-off-by: Bryn M. Reeves <bmr@redhat.com>